.\" Manpage for mstrie.
.\" Contact mikita.akulich@gmail.com to correct errors or typos.
.TH man 1 "04 March 2018" "0.1" "mstrie man page"
.SH NAME
mstrie \- Multiset-trie index manager
.SH SYNOPSIS
mstrie ...
.SH DESCRIPTION
The mstrie program is an interactive manager for the index data structure Multiset-trie.
.SH INTERPRETER INTERFACE
The interpreter interface resembles that of the UNIX shell. 
